### ISSUE TITLE
unable to download alljoyn source

### ISSUE THREAD

**Issue by scenaristeur** [nxhack/openwrt-arduino-packages#1]
Trying to build lede for yun , I got this issue : 

ime: package/feeds/packages/libcap/compile#2.43#0.66#4.16
make[3]: Entering directory '/home/david/dev/yun/openwrt/feeds/arduino/alljoyn'
mkdir -p /home/david/dev/yun/openwrt/dl
SHELL= flock /home/david/dev/yun/openwrt/tmp/.alljoyn-15.04.00b-src.tar.gz.flock -c '  	/home/david/dev/yun/openwrt/scripts/download.pl "/home/david/dev/yun/openwrt/dl" "alljoyn-15.04.00b-src.tar.gz" "749e820ac5379538025218c6507cc813ee6b24da55e0a6340474d694811fecf4" "" "https://allseenalliance.org/releases/alljoyn/15.04/"    '
Can't exec "curl": No such file or directory at /home/david/dev/yun/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --no-check-certificate --output-document=- https://allseenalliance.org/releases/alljoyn/15.04/alljoyn-15.04.00b-src.tar.gz
--2018-08-27 22:04:22--  https://allseenalliance.org/releases/alljoyn/15.04/alljoyn-15.04.00b-src.tar.gz
Resolving allseenalliance.org (allseenalliance.org)... 50.63.202.21
Connecting to allseenalliance.org (allseenalliance.org)|50.63.202.21|:443... failed: Connection timed out.
Retrying.

--2018-08-27 22:04:44--  (try: 2)  https://allseenalliance.org/releases/alljoyn/15.04/alljoyn-15.04.00b-src.tar.gz
Connecting to allseenalliance.org (allseenalliance.org)|50.63.202.21|:443... failed: Connection timed out.
Retrying.

--2018-08-27 22:05:06--  (try: 3)  https://allseenalliance.org/releases/alljoyn/15.04/alljoyn-15.04.00b-src.tar.gz
Connecting to allseenalliance.org (allseenalliance.org)|50.63.202.21|:443... failed: Connection timed out.
Retrying.

--2018-08-27 22:05:29--  (try: 4)  https://allseenalliance.org/releases/alljoyn/15.04/alljoyn-15.04.00b-src.tar.gz
Connecting to allseenalliance.org (allseenalliance.org)|50.63.202.21|:443... failed: Connection timed out.
Retrying.

--2018-08-27 22:05:53--  (try: 5)  https://allseenalliance.org/releases/alljoyn/15.04/alljoyn-15.04.00b-src.tar.gz
Connecting to allseenalliance.org (allseenalliance.org)|50.63.202.21|:443... failed: Connection timed out.
Giving up.

Download failed.
Can't exec "curl": No such file or directory at /home/david/dev/yun/openwrt/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --no-check-certificate --output-document=- https://sources.lede-project.org/alljoyn-15.04.00b-src.tar.gz
--2018-08-27 22:06:13--  https://sources.lede-project.org/alljoyn-15.04.00b-src.tar.gz
Resolving sources.lede-project.org (sources.lede-project.org)... 148.251.78.235, 2a01:4f8:202:43ea::3
Connecting to sources.lede-project.org (sources.lede-project.org)|148.251.78.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-27 22:06:13 ERROR 404: Not Found.

**Comment by nxhack** [comment]
Oh.. "allseenalliance.org" has disappeared. It seems that it is now being published on github so change it. Please wait a while.

**Comment by nxhack** [comment]
Merged
