### ISSUE TITLE
Upstream bossa to openwrt/packages?

### ISSUE THREAD

**Issue by PolynomialDivision** [nxhack/openwrt-arduino-packages#16]
Hi, I would like to upstream the bossa tool to OpenWrt. I hope this is okay?

https://github.com/nxhack/openwrt-arduino-packages/tree/master/bossa

**Comment by nxhack** [comment]
@PolynomialDivision 

I used to hack "YUN" a few years ago, but haven't touched it at all lately. If you'd like to override the maintainer of this package, I'd be happy to approve it.

**Comment by PolynomialDivision** [comment]
Great than I will merge this:
https://github.com/openwrt/packages/pull/16940

I need this to reflash microcontrollers from a banana pi r64. I need to call this script before I can flash, however I will need to convert it to c for easy use in openwrt:
```python
import serial

com = serial.Serial()
com.port = '/dev/ttyACM0'
com.baudrate = 1200
com.timeout = 1
com.stopbits = 1
com.parity = serial.PARITY_NONE
com.setDTR(False)
com.open()
com.close()
````
