### ISSUE TITLE
Your local docbook2man was found to work with SGML rather   than XML. 

### ISSUE THREAD

**Issue by scenaristeur** [nxhack/openwrt-arduino-packages#4]
もしもし  @nxhack

Moshimoshi

I've build LEDE 18.06 once when I was under Lubuntu 16.04 now I've upgraded to Lubuntu 18.04, I've this error. 
there was two folder for expat in /home/david/dev/yun/openwrt/build_dir/hostpkg : expat 2.2.5 & expat 2.2.6 . I've tried to delet the two & relaunch build.sh ( not rebuild.sh) and the problem is always here.
I can install docbook, not docbook2X on my Lubuntu, ??
And where do I have to change the variable DOCBOOK_TO_MAN ? on my system or in build .config file  ?

Thx

[...]
checking for working mmap... yes
checking for docbook2x-man... no
checking for db2x_docbook2man... no
checking for docbook2man... docbook2man
configure: error: Your local docbook2man was found to work with SGML rather
  than XML. Please install docbook2X and use variable DOCBOOK_TO_MAN to point
  configure to command docbook2x-man of docbook2X.
  Or use DOCBOOK_TO_MAN="xmlto man --skip-validation" if you have xmlto around.
  You can also configure using --without-docbook if you can do without a man
  page for xmlwf.
make[3]: *** [/home/david/dev/yun/openwrt/build_dir/hostpkg/expat-2.2.6/.configured] Error 1
Makefile:67: recipe for target '/home/david/dev/yun/openwrt/build_dir/hostpkg/expat-2.2.6/.configured' failed
make[3]: Leaving directory '/home/david/dev/yun/openwrt/feeds/packages/libs/expat'
Command exited with non-zero status 2
time: package/feeds/packages/expat/host-compile#34.53#4.15#41.35
make[2]: *** [package/feeds/packages/expat/host/compile] Error 2
package/Makefile:107: recipe for target 'package/feeds/packages/expat/host/compile' failed
make[2]: Leaving directory '/home/david/dev/yun/openwrt'
make[1]: *** [/home/david/dev/yun/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
package/Makefile:103: recipe for target '/home/david/dev/yun/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/home/david/dev/yun/openwrt'
make: *** [world] Error 2
/home/david/dev/yun/openwrt/include/toplevel.mk:216: recipe for target 'world' failed

**Comment by nxhack** [comment]
> configure: error: Your local docbook2man was found to work with SGML rather
than XML. Please install docbook2X and use variable DOCBOOK_TO_MAN to point
configure to command docbook2x-man of docbook2X.
Or use DOCBOOK_TO_MAN="xmlto man --skip-validation" if you have xmlto around.
You can also configure using --without-docbook if you can do without a man
page for xmlwf.


As shown in the error message. You may add "--without-docbook" to the Makefile.

https://github.com/openwrt/packages/blob/openwrt-18.06/libs/expat/Makefile

**Comment by nxhack** [comment]
```diff
diff --git a/tools/expat/Makefile b/tools/expat/Makefile
index 8d3f5bf..4242d8f 100644
--- a/tools/expat/Makefile
+++ b/tools/expat/Makefile
@@ -19,6 +19,8 @@ HOST_BUILD_PARALLEL:=1
 
 include $(INCLUDE_DIR)/host-build.mk
 
+HOST_CONFIGURE_ARGS+=--without-docbook
+
 define Host/Install
        $(MAKE) -C $(HOST_BUILD_DIR) install
 endef
```

**Comment by nxhack** [comment]
Merged.
https://github.com/openwrt/openwrt/commit/6e80dd58bb6c8c146ed8fd7ed538e96db4e8cc13
